<a href="https://www.kaggle.com/code/saramilani/numpy-fun-problems-beginner?scriptVersionId=193093518" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# My Solutions for Numpy Fun Problems - Beginner

In this notebook, I am exploring the "Beginner" level practice problems, available at the following source:

- [Practice Problems Source](https://www.practiceprobs.com/problemsets/python-numpy/beginner/)

To enhance your understanding and add more context to your learning, I recommend watching relevant educational content on YouTube. Here's a helpful resource I found:

- [YouTube Tutorial](https://www.youtube.com/watch?v=eClQWW_gbFk)

As you build your foundational skills with these beginner problems, you might want to challenge yourself with more complex tasks. To aid in this progression, I have also solved the "Intermediate" level problems, and you can find those solutions here:

- [Next Notebook: Numpy Fun Problems - Intermediate](https://www.kaggle.com/code/matinmahmoodi/numpy-fun-problems-intermediate)

I value your input and alternative approaches to these problems. Engaging in discussions can greatly enhance our collective learning experience, so please don't hesitate to comment with your feedback or solutions.

### **If you find this notebook beneficial, please consider showing your support with an upvote!**


# Q1 - High School Reunion Problem

https://www.practiceprobs.com/problemsets/python-numpy/beginner/high-school-reunion/

In [1]:
import numpy as np
dailywts = 185 - np.arange(5*7)/5

print(dailywts)


[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


Given these daily weights, build an array with your average weight per weekend1.


## Solution 1

In [2]:
(dailywts[5::7] + dailywts[6::7])/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

## Solution 2

In [3]:
dailywts.reshape(5,-1)[:, -2:].mean(axis=1)

array([183.9, 182.5, 181.1, 179.7, 178.3])

# Q2 - Nola Problem

https://www.practiceprobs.com/problemsets/python-numpy/beginner/nola/

Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.


In [4]:
"""
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
"""


'\n[[ 1  3  5  7  9 11 13]\n [17 19 21 23 25 27 29]\n [33 35 37 39 41 43 45]\n [49 51 53 55 57 59 61]]\n'

## Solution

In [5]:
np.arange(1, 65, 2).reshape(4,-1)[:, :-1]

array([[ 1,  3,  5,  7,  9, 11, 13],
       [17, 19, 21, 23, 25, 27, 29],
       [33, 35, 37, 39, 41, 43, 45],
       [49, 51, 53, 55, 57, 59, 61]])

# Q3 - Gold Miner Problem

https://www.practiceprobs.com/problemsets/python-numpy/beginner/gold-miner/

After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [6]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

print(gold)


locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])


[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


## Solution

In [7]:
gold[locs[:, 0], locs[:, 1]]

array([2, 6, 2, 8, 2])

# Q4 - Roux Problem

https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/

Define a  roux array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them.

In [8]:
# roux array of length 5
# [9 0 4 0 1]

In [9]:
# roux array of length 8
# [ 0 16  0  9  0  4  0  1]

Implement a function called make_roux(n) that inputs n, the desired size of the array, and outputs the corresponding roux array. Then test it on the examples above.


In [10]:
def make_roux(n):
    """returns a roux array of length n"""

    # your code here

## Solution

In [11]:
def make_roux(n):
    """returns a roux array of length n"""

    roux = np.zeros(shape=(n,), dtype='int64')
    nsquares = np.ceil(len(roux) / 2)
    squares = (1 + np.arange(nsquares)) ** 2
    roux[::-2] = squares

    return roux

In [12]:
roux_array_8 = make_roux(8)
roux_array_5 = make_roux(5)

print("roux array of length 8:")
print(roux_array_8)

print("\nroux array of length 5:")
print(roux_array_5)

roux array of length 8:
[ 0 16  0  9  0  4  0  1]

roux array of length 5:
[9 0 4 0 1]


# Q5 - Chic-fil-A Problem

https://www.practiceprobs.com/problemsets/python-numpy/beginner/chic-fil-a/

You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A 🐔.

You buy three billboards evenly spaced starting from mile marker 17 and ending on mile marker 28.
You buy another three billboards starting on mile marker 32 and ending on mile marker 36.
In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A.
Determine how far each B ad is from your restaurant which is located at mile marker 30.

In [13]:
# ads / restaurant*:   A     B     C   *   C  B  A
# billboards:        --|-----|-----|---|---|--|--|--
# mile markers:       17          28  30  32    36

## Solution

In [14]:
dists = np.abs(np.linspace([17,32], [28,36], num=3, axis=1) - 30)
dists[[0,1], [1,1]]

array([7.5, 4. ])